project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "explore/**/*.qmd"
    - "groups/**/*.qmd"
    - "news/**/*.qmd"

website:
  title: "SHIFT"
  favicon: public/icon.svg
  page-navigation: true
  site-url: "https://dhc-shift.github.io"
  repo-url: "https://github.com/dhc-shift/dhc-shift.github.io"
  search:
    location: navbar
    type: overlay
  navbar:
    logo: public/icon.svg
    title: "SHIFT"
    right:
      - text: "About"
        href: about.qmd
      - text: "Activities"
        href: activities.qmd
      - text: "Explore"
        href: explore/index.qmd
      - text: "Groups"
        href: groups/index.qmd
      - text: "News"
        href: news/index.qmd
      - text: "Join"
        href: join.qmd
      - icon: github
        href: https://github.com/dhc-shift/dhc-shift.github.io
  page-footer:
    left: "Site made with [Quarto](https://quarto.org/)."
    right:
      - icon: github
        href: https://github.com/dhc-shift/dhc-shift.github.io

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    toc-title: "On this page"
    smooth-scroll: true
    highlight-style: github
    link-external-newwindow: true

execute:
  freeze: false
